apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment  # cluster deployment name for app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2 # deployment selector label for app2. It should match the label names in the template
  template:
    metadata:
      labels:
        app: app2 # pod label creator for app2. It should match the deployment selector label.
    spec:
      containers:
        - name: app2
          image: paulbouwer/hello-kubernetes:1.10.1
          env:
            - name: MESSAGE
              value: "Hello from App 2"
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: app2-service  # cluster service name for app2
spec:
  type: ClusterIP #default
  selector:
    app: app2 # Service selector label. Must match Deployment .spec.template.metadata.labels and .spec.selector.matchLabels
  ports:
    - port: 80
      targetPort: 8080