apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment  # deployment name 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app2 # deployment label found the pod
  template:
    metadata:
      labels:
        app: app2 # pod label tag prefix
    spec:
      containers:
        - name: app2
          image: paulbouwer/hello-kubernetes:1.10.1
          env:
            - name: MESSAGE
              value: "Hello from App 2"
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: app2-service  # service name
spec:
  type: ClusterIP #default
  selector:
    app: app2 # Service label forward traffic to the pods
  ports:
    - port: 80
      targetPort: 8080