Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_architecture = "amd64"
  config.ssh.insert_key = true

  config.vm.define "bkasS" do |machine|
    machine.vm.hostname = "bkasS"
    machine.vm.network "private_network", ip: "192.168.56.110"

    machine.vm.provider "virtualbox" do |vb|
      vb.name = "bkasS-p2"
      vb.cpus = 1
      vb.memory = 1024
    end

    machine.vm.provision "shell", path: "scripts/install_k3s_server.sh", privileged: true
    machine.vm.provision "shell", path: "scripts/apply_manifests.sh", privileged: true
  end
end
