Vagrant.configure(2) do |config|
  config.vm.box = "bento/debian-12"
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
  
  config.vm.define "bkasS" do |master|
    master.vm.hostname = "bkasS"
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.provider "virtualbox" do |vm|
      vm.name = "bkasS"
      vm.cpus = 2
      vm.memory = 3072
    end
    master.vm.provision "shell", path: "scripts/install_k3s_server.sh"
  end
  
  config.vm.define "bkasSW" do |worker|
    worker.vm.hostname = "bkasSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provider "virtualbox" do |vm|
      vm.name = "bkasSW"
      vm.cpus = 2
      vm.memory = 3072
    end
    worker.vm.provision "shell", path: "scripts/install_k3s_worker.sh"
  end
end