Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.define "bkasS-p3" do |vm|
    vm.vm.hostname = "bkasS"

    vm.vm.network "private_network", ip: "192.168.56.110"

    vm.vm.provider "virtualbox" do |vb|
      vb.name = "bkasS-p3"
      vb.cpus = 2
      vb.memory = 2048
    end

    vm.vm.provision "shell", path: "scripts/setup.sh"
  end
end
